call plug#begin('~/.vim/plugged')

Plug 'fatih/vim-go' "install vim-go plugin

call plug#end()

"remove/add imports when saving
let g:go_fmt_command = "goimports"

" Copy to clipboard
vmap <C-C> "+y

" fuzzy-find
set rtp+=/usr/local/opt/fzf
map <C-P> :FZF<CR>
nmap ; :FZF<CR>

" Persistent Undo
set undofile
set undodir=~/.vim/undodir

" tab setting
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set hidden

" enable mouse functionality
set mouse=a

"coloscheme
set background=dark
"colorscheme molokai
colorscheme monokai

"syntax highlighting
syntax enable
let g:go_highlight_build_constraints = 1
let g:go_highlight_extra_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_structs = 1
let g:go_highlight_types = 1

"statusline
set statusline=%F

