set number
filetype plugin indent on
set tabstop=2
set shiftwidth=2
set expandtab

"filetype off
"filetype plugin indent off
"set runtimepath+=$GOROOT/misc/vim
"filetype plugin indent on
"syntax enable 

"au BufRead,BufNewFile *.go set filetype=go

syntax enable  
filetype plugin on  
set number  
set hlsearch
let g:go_disable_autoinstall = 0


" Highlight
let g:go_highlight_functions = 1  
let g:go_highlight_methods = 1  
let g:go_highlight_structs = 1  
let g:go_highlight_operators = 1  
let g:go_highlight_build_constraints = 1

inoremap jk <esc>
inoremap <esc> <NOP>
nnoremap er $
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <NOP>
noremap <Right> <NOP>
