call plug#begin('~/.vim/plugged')

" helpful utils
Plug 'tpope/vim-commentary'

" coloscheme
Plug 'morhetz/gruvbox'

" lightline
Plug 'itchyny/lightline.vim'
Plug 'itchyny/vim-gitbranch'

" navigation shortcuts
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'tpope/vim-surround'

" Golang plugin
Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }

Plug 'psliwka/vim-smoothie'

call plug#end()

" ================================
" General Settings
" ================================
set mouse=a
set number
set nofoldenable
set background=dark
" syntax enable
let g:gruvbox_contrast_dark='soft'
colorscheme gruvbox

" set iterm tab to file basename
set title
set titlestring=%t

" Copy to clipboard
vmap <C-C> "+y

" Fuzzy-find
set rtp+=/usr/local/opt/fzf
map <C-P> :FZF<CR>

" Persistent Undo
set undofile
set undodir=~/.vim/undodir

" Spacing
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4

" Hightlight trailing spaces in red
:highlight ExtraWhitespace ctermbg=red guibg=red
:match ExtraWhitespace /\s\+$/

" ================================
" Golang Settings
" =================================
let g:go_fmt_command = "goimports"
let g:go_fmt_autosave = 1

au FileType go set noexpandtab
au FileType go set shiftwidth=4
au FileType go set softtabstop=4
au FileType go set tabstop=4

" let g:go_highlight_build_constraints = 1
" let g:go_highlight_extra_types = 1
" let g:go_highlight_fields = 1
" let g:go_highlight_functions = 1
" let g:go_highlight_methods = 1
" let g:go_highlight_operators = 1
" let g:go_highlight_structs = 1
" let g:go_highlight_types = 1
" let g:go_highlight_variable_declarations = 1

" ==========================
" Custom settings
" ==========================

" center the line when jumping to it
nnoremap gg ggzz

" move up and down single screen row
nnoremap j gj
nnoremap k gk
nnoremap <up> g<up>
nnoremap <down> g<down>

" Lowercase highlight upper case but not the other way around
set incsearch
set ignorecase
set smartcase
set hlsearch
set cursorline " Highlight the current line

nmap S  :%s//g<LEFT><LEFT>
vmap S  :s//g<LEFT><LEFT>

let g:lightline = {
    \ 'colorscheme': 'gruvbox',
    \ 'active': {
    \   'left': [ [ 'mode', 'paste' ],
    \             [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
    \ },
    \ 'component_function': {
    \   'gitbranch': 'gitbranch#name'
    \ },
\ }

noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

