### KEVIN's SETTINGS
#export PS1="\[\033[38;5;32m\]\s-\v\\[$(tput sgr0)\]: \w\n\\$ \[$(tput sgr0)\]\e[0m"
export PS1="\s-\v: \w\n\\$ "

export LSCOLORS="Exfxcxdxbxegedabagacad"
alias ls="ls -G"

alias vim="nvim"
alias pp="vim ~/.bash_profile"
alias rr="source ~/.bash_profile"
alias vrc="vim ~/.vimrc"
alias ll="ls -la"
