#!/bin/bash

export CLICOLOR=1
export PS1="\u@\h:\[$(tput sgr0)\]\[\033[38;5;33m\][\w]\[$(tput sgr0)\]\[\033[38;5;15m\]\\$ \[$(tput sgr0)\]"
export GOPATH="/home/github"
export PATH=/usr/local/Cellar/ruby/2.4.2/bin:$PATH

alias rr="source ~/.bash_profile"
alias profile="vim ~/.bash_profile"
